# Generated by Django 6.0 on 2025-12-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="updated_at",
        ),
    ]
