# Generated by Django 6.0 on 2025-12-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_wallet_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mobile_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
