# Generated by Django 6.0 on 2025-12-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_otp_userprofile_otp_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="otp_verified",
        ),
    ]
